--- #YAML:1.0
name                        : DBD-Pg
version                     : 3.15.1
abstract                    : DBI PostgreSQL interface
author:              
  - Greg Sabino Mullane <greg@turnstep.com>

license                     : perl
distribution_type           : module
dynamic_config              : 1

requires:
  DBI                       : 1.614
  perl                      : 5.008001
  version                   : 0
build_requires:
  DBI                       : 1.614
  File::Temp                : 0
  Test::More                : 0.88
  Time::HiRes               : 0
  version                   : 0
configure_requires:
  DBI                       : 1.614
  version                   : 0
recommends:
  Cwd                       : 0
  Encode                    : 0
  Module::Signature         : 0.50

provides:
  DBD::Pg:
    file                    : Pg.pm
    version                 : 3.15.1
  Bundle::DBD::Pg:
    file                    : lib/Bundle/DBD/Pg.pm
    version                 : 3.15.1

keywords:
  - Postgres
  - PostgreSQL
  - DBI
  - libpq
  - dbdpg

resources:
  homepage                  : http://search.cpan.org/dist/DBD-Pg/
  license                   : http://dev.perl.org/licenses/
  bugtracker                : https://github.com/bucardo/dbdpg/issues
  repository                : https://github.com/bucardo/dbdpg
  MailingList               : http://www.nntp.perl.org/group/perl.dbd.pg/
  IRC                       : irc://irc.libera.chat/#postgresql

meta-spec:
  version                   : 1.4
  url                       : http://module-build.sourceforge.net/META-spec-v1.4.html

generated_by                : emacs
