--- #YAML:1.0
name                        : DBD-Pg
version                     : 2.19.1
abstract                    : DBI PostgreSQL interface
author:              
  - Greg Sabino Mullane <greg@turnstep.com>

license                     : perl
distribution_type           : module
dynamic_config              : 1

requires:
  DBI                       : 1.52
  perl                      : 5.006001
  version                   : 0
build_requires:
  DBI                       : 1.52
  Test::More                : 0.61
  Time::HiRes               : 0
  version                   : 0
configure_requires:
  DBI                       : 1.52
  version                   : 0
recommends:
  Cwd                       : 0
  Encode                    : 0
  File::Temp                : 0
  Module::Signature         : 0.50

provides:
  DBD::Pg:
    file                    : Pg.pm
    version                 : 2.19.1
  Bundle::DBD::Pg:
    file                    : lib/Bundle/DBD/Pg.pm
    version                 : 2.19.1

keywords:
  - Postgres
  - PostgreSQL
  - DBI
  - libpq
  - dbdpg

resources:
  homepage                  : http://search.cpan.org/dist/DBD-Pg/
  license                   : http://dev.perl.org/licenses/
  bugtracker                : http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-Pg
  repository                : git://bucardo.org/dbdpg.git
  MailingList               : http://www.nntp.perl.org/group/perl.dbd.pg/

meta-spec:
  version                   : 1.4
  url                       : http://module-build.sourceforge.net/META-spec-v1.4.html

generated_by                : emacs
